### ISSUE TITLE
Please review my code

### ISSUE THREAD

**Issue by Siyasanga** [Siyasanga/registration_numbers_webapp#1]
Hi  @knzulu16 and @SinethembaDlova I need your help with reviewing my code.
Please feel free to fork it and run on your machine then send me feedback.

Warm regards,
Siyasanga Mtshokotsha

**Comment by knzulu16** [comment]
Hello@ Siyasanga i forked your registration app as per your documentation, It is working well.You did an awesome job.

**Comment by Siyasanga** [comment]
Thank you @knzulu16

**Comment by sinethembadlova** [comment]
Hi @Siyasanga ,

I followed all the steps in the read me and the app worked perfectly. Thanks.
